on:
  push:
    branches:
      - publish

jobs:
  deploy:
    name: Deploy website to Github Pages with Gatsby
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node_version: [16.x]
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Setting Git credentials
        run: git config --global user.email "woojiahao1234@gmail.com" && git config --global user.name "woojiahao"

      - name: Setup Node.js version ${{ matrix.node_version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node_version }}

      - name: Installing Gatsby
        run: yarn install --no-optional

      - name: Deploy the site
        run: yarn deploy
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          GOOGLE_ANALYTICS: ${{ secrets.GOOGLE_ANALYTICS }}
